name: vaxen-api-dev

services:
  api:
    image: alpine:3.20
    ports:
      - "8080:8080"
    volumes:
      - ./bin/dev_server:/bin/dev_server
    working_dir: /app
    command: ["/bin/dev_server"]
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - vaxen_network

  db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-vaxen}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vaxen_network

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - vaxen_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - vaxen_network

volumes:
  postgres_data:
  redis_data:

networks:
  vaxen_network:
    driver: bridge
